[project]
name = "affiliate-chain"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.affiliate]
path = "contracts/affiliate.clar"
depends_on = []

[contracts.affiliate-leaderboard]
path = "contracts/affiliate-leaderboard.clar"
depends_on = []

[contracts.payout-manager]
path = "contracts/payout-manager.clar"
depends_on = []

[contracts.product-manager]
path = "contracts/product-manager.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
